//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssp7wq_irf_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Musor = new HashSet<Musor>();
        }
    
        public int Id_Film { get; set; }
        public string Cím { get; set; }
        public string Kiadas_eve { get; set; }
        public string Rendezo { get; set; }
        public string Mufaj { get; set; }
        public string Nyelv { get; set; }
        public string Felirat { get; set; }
        public int Hossz_perc_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musor> Musor { get; set; }
    }
}
