//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssp7wq_irf_project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mozi_jegy_musor_kezelesEntities : DbContext
    {
        public Mozi_jegy_musor_kezelesEntities()
            : base("name=Mozi_jegy_musor_kezelesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Foglalas> Foglalas { get; set; }
        public virtual DbSet<Musor> Musor { get; set; }
        public virtual DbSet<Terem> Terem { get; set; }
    }
}
